<?php

namespace App\Models;

use App\Models\FunctionModel;

class WebsiteProfileModel extends FunctionModel
{
    protected $table            = 'website_profile';
    protected $primaryKey       = 'website_profile_id';
    protected $useAutoIncrement = true;
    protected $returnType       = 'array';
    protected $useSoftDeletes   = false;
    protected $protectFields    = true;
    protected $allowedFields = [
        'website_profile_id',
        'firm_name',
        'firm_slogan',
        'firm_logo_url',
        'firm_address',
        'firm_cin_no',
        'firm_gst_no',
        'firm_pan_no',
        'contact_mobile',
        'contact_email',
        'contact_whatsapp',
        'sales_mobile',
        'sales_email',
        'sales_whatsapp',
        'support_mobile',
        'support_email',
        'support_whatsapp',
        'career_mobile',
        'career_email',
        'career_whatsapp',
        'firm_address_gmap_url',
        'website_url',
        'play_store_url',
        'app_store_url',
        'facebook_url',
        'instagram_url',
        'twitter_url',
        'linkedin_url',
        'youtube_url',
        'pinterest_url',
        'telegram_url',
        'google_search_url',
        'home_page_seo_title',
        'home_page_seo_keyword',
        'home_page_seo_description',
        'home_page_content',
        'about_page_seo_title',
        'about_page_seo_keyword',
        'about_page_seo_description',
        'about_page_content',
        'contact_page_seo_title',
        'contact_page_seo_keyword',
        'contact_page_seo_description',
        'contact_page_content',
        'google_embaded_iframe',
        'support_page_seo_title',
        'support_page_seo_keyword',
        'support_page_seo_description',
        'support_page_content',
        'career_page_seo_title',
        'career_page_seo_keyword',
        'career_page_seo_description',
        'career_page_content',
        'faq_page_seo_title',
        'faq_page_seo_keyword',
        'faq_page_seo_description',
        'faq_page_content',
        'tc_page_seo_title',
        'tc_page_seo_keyword',
        'tc_page_seo_description',
        'tc_page_content',
        'pp_page_seo_title',
        'pp_page_seo_keyword',
        'pp_page_seo_description',
        'pp_page_content',
        'shipping_policy_page_seo_title',
        'shipping_policy_page_seo_keyword',
        'shipping_policy_page_seo_description',
        'shipping_policy_page_content',
        'return_page_seo_title',
        'return_page_seo_keyword',
        'return_page_seo_description',
        'return_page_content',
        'refund_page_seo_title',
        'refund_page_seo_keyword',
        'refund_page_seo_description',
        'refund_page_content',
        'disclaimer_page_seo_title',
        'disclaimer_page_seo_keyword',
        'disclaimer_page_seo_description',
        'disclaimer_page_content',
        'image_slider_web_img_1',
        'image_slider_web_img_alt_1',
        'image_slider_web_redirect_url_1',
        'image_slider_web_img_2',
        'image_slider_web_img_alt_2',
        'image_slider_web_redirect_url_2',
        'image_slider_web_img_3',
        'image_slider_web_img_alt_3',
        'image_slider_web_redirect_url_3',
        'image_slider_web_img_4',
        'image_slider_web_img_alt_4',
        'image_slider_web_redirect_url_4',
        'image_slider_web_img_5',
        'image_slider_web_img_alt_5',
        'image_slider_web_redirect_url_5',

        'image_slider_mob_img_1',
        'image_slider_mob_img_alt_1',
        'image_slider_mob_redirect_url_1',
        'image_slider_mob_img_2',
        'image_slider_mob_img_alt_2',
        'image_slider_mob_redirect_url_2',
        'image_slider_mob_img_3',
        'image_slider_mob_img_alt_3',
        'image_slider_mob_redirect_url_3',
        'image_slider_mob_img_4',
        'image_slider_mob_img_alt_4',
        'image_slider_mob_redirect_url_4',
        'image_slider_mob_img_5',
        'image_slider_mob_img_alt_5',
        'image_slider_mob_redirect_url_5',
        'is_refer_coupon_active',
        'refer_coupon_calculation_type',
        'refer_coupon_value',
        'refer_coupon_min_order_value',
        'refer_coupon_max_order_value',
        'refer_coupon_valid_days',
        'refer_coupon_send',
        'level1',
        'level1_commission_percentage',
        'level2',
        'level2_commission_percentage',
        'wallet_activation_amount',
        'wallet_withdrawal_amount',
        'firm_pincode',
        'pickup_location',
        'order_tracking_url'

    ];
    protected bool $allowEmptyInserts = false;
    protected bool $updateOnlyChanged = true;
    protected $messageAlias = "Profile";
    protected array $casts = [];
    protected array $castHandlers = [];

    // Dates
    protected $useTimestamps = false;
    protected $dateFormat    = 'datetime';
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';

    // Validation

    protected $validationRules = [
        "website_profile_id" => "permit_empty",
        "firm_name" => "required",
        "firm_slogan" => "permit_empty",
        "firm_logo_url" => "permit_empty",
        "firm_address" => "permit_empty",
        "firm_cin_no" => "permit_empty",
        "firm_gst_no" => "permit_empty|min_length[15]|max_length[15]",
        "firm_pan_no" => "permit_empty",
        'firm_pincode' => 'required|max_length[6]',
        "contact_mobile" => "permit_empty|max_length[10]",
        "contact_email" => "permit_empty|valid_email",
        "contact_whatsapp" => "permit_empty|max_length[10]",
        "sales_mobile" => "permit_empty",
        "sales_email" => "permit_empty|valid_email",
        "sales_whatsapp" => "permit_empty",
        "support_mobile" => "permit_empty",
        "support_email" => "permit_empty|valid_email",
        "support_whatsapp" => "permit_empty",
        "career_mobile" => "permit_empty|max_length[10]",
        "career_email" => "permit_empty|valid_email",
        "career_whatsapp" => "permit_empty|max_length[10]",
        "firm_address_gmap_url" => "permit_empty",
        "website_url" => "permit_empty",
        "play_store_url" => "permit_empty",
        "app_store_url" => "permit_empty",
        "facebook_url" => "permit_empty",
        "instagram_url" => "permit_empty",
        "twitter_url" => "permit_empty",
        "linkedin_url" => "permit_empty",
        "youtube_url" => "permit_empty",
        "pinterest_url" => "permit_empty",
        "telegram_url" => "permit_empty",
        "google_search_url" => "permit_empty",
        "home_page_seo_title" => "permit_empty|max_length[60]",
        "home_page_seo_keyword" => "permit_empty",
        "home_page_seo_description" => "permit_empty|max_length[170]",
        "home_page_content" => "permit_empty",
        "about_page_seo_title" => "permit_empty|max_length[60]",
        "about_page_seo_keyword" => "permit_empty",
        "about_page_seo_description" => "permit_empty|max_length[170]",
        "about_page_content" => "permit_empty",
        "contact_page_seo_title" => "permit_empty|max_length[60]",
        "contact_page_seo_keyword" => "permit_empty",
        "contact_page_seo_description" => "permit_empty|max_length[170]",
        "contact_page_content" => "permit_empty",
        "google_embaded_iframe" => "permit_empty",
        "support_page_seo_title" => "permit_empty|max_length[60]",
        "support_page_seo_keyword" => "permit_empty",
        "support_page_seo_description" => "permit_empty|max_length[170]",
        "support_page_content" => "permit_empty",
        "career_page_seo_title" => "permit_empty|max_length[60]",
        "career_page_seo_keyword" => "permit_empty",
        "career_page_seo_description" => "permit_empty|max_length[170]",
        "career_page_content" => "permit_empty",
        "faq_page_seo_title" => "permit_empty|max_length[60]",
        "faq_page_seo_keyword" => "permit_empty",
        "faq_page_seo_description" => "permit_empty|max_length[170]",
        "faq_page_content" => "permit_empty",
        "tc_page_seo_title" => "permit_empty|max_length[60]",
        "tc_page_seo_keyword" => "permit_empty",
        "tc_page_seo_description" => "permit_empty|max_length[170]",
        "tc_page_content" => "permit_empty",
        "pp_page_seo_title" => "permit_empty|max_length[60]",
        "pp_page_seo_keyword" => "permit_empty",
        "pp_page_seo_description" => "permit_empty|max_length[170]",
        "pp_page_content" => "permit_empty",
        "shipping_policy_page_seo_title"  => "permit_empty",
        "shipping_policy_page_seo_keyword" => "permit_empty",
        "shipping_policy_page_seo_description"  => "permit_empty",
        "shipping_policy_page_content"   => "permit_empty",
        "return_page_seo_title" => "permit_empty|max_length[60]",
        "return_page_seo_keyword" => "permit_empty",
        "return_page_seo_description" => "permit_empty|max_length[170]",
        "return_page_content" => "permit_empty",
        "refund_page_seo_title" => "permit_empty|max_length[60]",
        "refund_page_seo_keyword" => "permit_empty",
        "refund_page_seo_description" => "permit_empty|max_length[170]",
        "refund_page_content" => "permit_empty",
        "disclaimer_page_seo_title" => "permit_empty|max_length[60]",
        "disclaimer_page_seo_keyword" => "permit_empty",
        "disclaimer_page_seo_description" => "permit_empty|max_length[170]",
        "disclaimer_page_content" => "permit_empty",
        'image_slider_web_img_1' => 'permit_empty',
        'image_slider_web_img_alt_1' => 'permit_empty',
        'image_slider_web_redirect_url_1' => 'permit_empty',
        'image_slider_web_img_2' => 'permit_empty',
        'image_slider_web_img_alt_2' => 'permit_empty',
        'image_slider_web_redirect_url_2' => 'permit_empty',
        'image_slider_web_img_3' => 'permit_empty',
        'image_slider_web_img_alt_3' => 'permit_empty',
        'image_slider_web_redirect_url_3' => 'permit_empty',
        'image_slider_web_img_4' => 'permit_empty',
        'image_slider_web_img_alt_4' => 'permit_empty',
        'image_slider_web_redirect_url_4' => 'permit_empty',
        'image_slider_web_img_5' => 'permit_empty',
        'image_slider_web_img_alt_5' => 'permit_empty',
        'image_slider_web_redirect_url_5' => 'permit_empty',
        'image_slider_mob_img_1' => 'permit_empty',
        'image_slider_mob_img_alt_1' => 'permit_empty',
        'image_slider_mob_redirect_url_1' => 'permit_empty',
        'image_slider_mob_img_2' => 'permit_empty',
        'image_slider_mob_img_alt_2' => 'permit_empty',
        'image_slider_mob_redirect_url_2' => 'permit_empty',
        'image_slider_mob_img_3' => 'permit_empty',
        'image_slider_mob_img_alt_3' => 'permit_empty',
        'image_slider_mob_redirect_url_3' => 'permit_empty',
        'image_slider_mob_img_4' => 'permit_empty',
        'image_slider_mob_img_alt_4' => 'permit_empty',
        'image_slider_mob_redirect_url_4' => 'permit_empty',
        'image_slider_mob_img_5' => 'permit_empty',
        'image_slider_mob_img_alt_5' =>  'permit_empty',
        'image_slider_mob_redirect_url_5' => 'permit_empty',
        'level1' => 'permit_empty',
        'level1_commission_percentage' => 'permit_empty',
        'level2' => 'permit_empty',
        'level2_commission_percentage' => 'permit_empty',
        'wallet_activation_amount' => 'permit_empty',
        'wallet_withdrawal_amount' => 'permit_empty',
        'pickup_location' => 'required',
        'order_tracking_url' => 'permit_empty'
    ];

    protected $validationMessages = [
        'firm_name.required' => 'The firm name field is required.',
        'firm_gst_no.min_length' => 'GST number must be exactly 15 characters long.',
        'firm_gst_no.max_length' => 'GST number must be exactly 15 characters long.',
        'firm_pincode.required' => 'The firm pincode field is required.',
        'firm_pincode.max_length' => 'Pincode must be exactly 6 characters long.',
        'contact_email.valid_email' => 'Please enter a valid email address for contact email.',
        'sales_email.valid_email' => 'Please enter a valid email address for sales email.',
        'support_email.valid_email' => 'Please enter a valid email address for support email.',
        'career_email.valid_email' => 'Please enter a valid email address for career email.',
        'home_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the home page (max 60 characters).',
        'home_page_seo_keyword.max_length' => 'Maximum length exceeded for Meta keywords on the home page (max 70 characters).',
        'home_page_seo_description.max_length' => 'Maximum length exceeded for Meta description on the home page (max 170 characters).',
        'firm_name.required' => 'The firm name field is required.',
        'firm_slogan.permit_empty' => 'The firm slogan field can be empty.',
        'firm_logo_url.permit_empty' => 'The firm logo URL can be empty.',
        'firm_address.permit_empty' => 'The firm address can be empty.',
        'firm_cin_no.permit_empty' => 'The firm CIN number can be empty.',
        'firm_gst_no.permit_empty' => 'The firm GST number can be empty.',
        'firm_pan_no.permit_empty' => 'The firm PAN number can be empty.',
        'contact_mobile.permit_empty' => 'The contact mobile can be empty.',
        'contact_mobile.max_length' => 'Mobile number cannot exceed 10 digits.',
        'contact_email.permit_empty' => 'The contact email can be empty.',
        'contact_whatsapp.permit_empty' => 'The contact WhatsApp can be empty.',
        'contact_whatsapp.max_length' => 'Mobile number cannot exceed 10 digits.',
        'sales_mobile.permit_empty' => 'The sales mobile can be empty.',
        'sales_email.permit_empty' => 'The sales email can be empty.',
        'sales_whatsapp.permit_empty' => 'The sales WhatsApp can be empty.',
        'support_mobile.permit_empty' => 'The support mobile can be empty.',
        'support_email.permit_empty' => 'The support email can be empty.',
        'support_whatsapp.permit_empty' => 'The support WhatsApp can be empty.',
        'career_mobile.permit_empty' => 'The career mobile can be empty.',
        'career_mobile.max_length' => 'Mobile number cannot exceed 10 digits.',
        'career_email.permit_empty' => 'The career email can be empty.',
        'career_whatsapp.permit_empty' => 'The career WhatsApp can be empty.',
        'career_whatsapp.max_length' => 'Mobile number cannot exceed 10 digits.',
        'firm_address_gmap_url.permit_empty' => 'The firm address Google Map URL can be empty.',
        'website_url.permit_empty' => 'The website URL can be empty.',
        'play_store_url.permit_empty' => 'The Play Store URL can be empty.',
        'app_store_url.permit_empty' => 'The App Store URL can be empty.',
        'facebook_url.permit_empty' => 'The Facebook URL can be empty.',
        'instagram_url.permit_empty' => 'The Instagram URL can be empty.',
        'twitter_url.permit_empty' => 'The Twitter URL can be empty.',
        'linkedin_url.permit_empty' => 'The LinkedIn URL can be empty.',
        'youtube_url.permit_empty' => 'The YouTube URL can be empty.',
        'pinterest_url.permit_empty' => 'The Pinterest URL can be empty.',
        'telegram_url.permit_empty' => 'The Telegram URL can be empty.',
        'google_search_url.permit_empty' => 'The Google Search URL can be empty.',

        /// Pages
        'home_page_seo_title.permit_empty' => 'The home page Tag title can be empty.',
        'home_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the home page (max 60 characters).',
        'home_page_seo_keyword.permit_empty' => 'The home page SEO keywords can be empty.',
        'home_page_seo_keyword.max_length' => 'Maximum length exceeded for SEO keywords on the home page (max 70 characters).',
        'home_page_seo_description.permit_empty' => 'The home page SEO description can be empty.',
        'home_page_seo_description.max_length' => 'Maximum length exceeded for SEO description on the home page (max 170 characters).',
        'home_page_content.permit_empty' => 'The home page content can be empty.',

        'about_page_seo_title.permit_empty' => 'The about page Tag title can be empty.',
        'about_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the about page (max 60 characters).',
        'about_page_seo_keyword.permit_empty' => 'The about page SEO keywords can be empty.',
        'about_page_seo_keyword.max_length' => 'Maximum length exceeded for SEO keywords on the about page (max 70 characters).',
        'about_page_seo_description.permit_empty' => 'The about page SEO description can be empty.',
        'about_page_seo_description.max_length' => 'Maximum length exceeded for SEO description on the about page (max 170 characters).',
        'about_page_content.permit_empty' => 'The about page content can be empty.',

        'contact_page_seo_title.permit_empty' => 'The contact page Tag title can be empty.',
        'contact_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the contact page (max 60 characters).',
        'contact_page_seo_keyword.permit_empty' => 'The contact page SEO keywords can be empty.',
        'contact_page_seo_keyword.max_length' => 'Maximum length exceeded for SEO keywords on the contact page (max 70 characters).',
        'contact_page_seo_description.permit_empty' => 'The contact page SEO description can be empty.',
        'contact_page_seo_description.max_length' => 'Maximum length exceeded for SEO description on the contact page (max 170 characters).',
        'contact_page_content.permit_empty' => 'The contact page content can be empty.',

        'support_page_seo_title.permit_empty' => 'The support page Tag title can be empty.',
        'support_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the support page (max 60 characters).',
        'support_page_seo_keyword.permit_empty' => 'The support page SEO keywords can be empty.',
        'support_page_seo_keyword.max_length' => 'Maximum length exceeded for SEO keywords on the support page (max 70 characters).',
        'support_page_seo_description.permit_empty' => 'The support page SEO description can be empty.',
        'support_page_seo_description.max_length' => 'Maximum length exceeded for SEO description on the support page (max 170 characters).',
        'support_page_content.permit_empty' => 'The support page content can be empty.',

        'career_page_seo_title.permit_empty' => 'The career page Tag title can be empty.',
        'career_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the career page (max 60 characters).',
        'career_page_seo_keyword.permit_empty' => 'The career page SEO keywords can be empty.',
        'career_page_seo_keyword.max_length' => 'Maximum length exceeded for SEO keywords on the career page (max 70 characters).',
        'career_page_seo_description.permit_empty' => 'The career page SEO description can be empty.',
        'career_page_seo_description.max_length' => 'Maximum length exceeded for SEO description on the career page (max 170 characters).',
        'career_page_content.permit_empty' => 'The career page content can be empty.',
        'faq_page_seo_title.permit_empty' => 'The FAQ page Tag title can be empty.',
        'faq_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the FAQ page (max 60 characters).',
        'faq_page_seo_keyword.permit_empty' => 'The FAQ page SEO keywords can be empty.',
        'faq_page_seo_keyword.max_length' => 'Maximum length exceeded for SEO keywords on the FAQ page (max 70 characters).',
        'faq_page_seo_description.permit_empty' => 'The FAQ page SEO description can be empty.',
        'faq_page_seo_description.max_length' => 'Maximum length exceeded for SEO description on the FAQ page (max 170 characters).',
        'faq_page_content.permit_empty' => 'The FAQ page content can be empty.',

        'tc_page_seo_title.permit_empty' => 'The Terms and Conditions page Tag title can be empty.',
        'tc_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the Terms and Conditions page (max 60 characters).',
        'tc_page_seo_keyword.permit_empty' => 'The Terms and Conditions page SEO keywords can be empty.',
        'tc_page_seo_keyword.max_length' => 'Maximum length exceeded for SEO keywords on the Terms and Conditions page (max 70 characters).',
        'tc_page_seo_description.permit_empty' => 'The Terms and Conditions page SEO description can be empty.',
        'tc_page_seo_description.max_length' => 'Maximum length exceeded for SEO description on the Terms and Conditions page (max 170 characters).',
        'tc_page_content.permit_empty' => 'The Terms and Conditions page content can be empty.',

        'pp_page_seo_title.permit_empty' => 'The Privacy Policy page Tag title can be empty.',
        'pp_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the Privacy Policy page (max 60 characters).',
        'pp_page_seo_keyword.permit_empty' => 'The Privacy Policy page SEO keywords can be empty.',
        'pp_page_seo_keyword.max_length' => 'Maximum length exceeded for SEO keywords on the Privacy Policy page (max 70 characters).',
        'pp_page_seo_description.permit_empty' => 'The Privacy Policy page SEO description can be empty.',
        'pp_page_seo_description.max_length' => 'Maximum length exceeded for SEO description on the Privacy Policy page (max 170 characters).',
        'pp_page_content.permit_empty' => 'The Privacy Policy page content can be empty.',


        'shipping_policy_page_seo_title.permit_empty' => 'The Shipping Policy page Tag title can be empty.',
        'shipping_policy_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the Shipping Policy page (max 60 characters).',
        'shipping_policy_page_seo_keyword.permit_empty' => 'The Shipping Policy page SEO keywords can be empty.',
        'shipping_policy_page_seo_keyword.max_length' => 'Maximum length exceeded for SEO keywords on the Shipping Policy page (max 70 characters).',
        'shipping_policy_page_seo_description.permit_empty' => 'The Shipping Policy page SEO description can be empty.',
        'shipping_policy_page_seo_description.max_length' => 'Maximum length exceeded for SEO description on the Shipping Policy page (max 170 characters).',
        'shipping_policy_page_content.permit_empty' => 'The Shipping Policy page content can be empty.',

        'return_page_seo_title.permit_empty' => 'The Return Policy page Tag title can be empty.',
        'return_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the Return Policy page (max 60 characters).',
        'return_page_seo_keyword.permit_empty' => 'The Return Policy page SEO keywords can be empty.',
        'return_page_seo_keyword.max_length' => 'Maximum length exceeded for SEO keywords on the Return Policy page (max 70 characters).',
        'return_page_seo_description.permit_empty' => 'The Return Policy page SEO description can be empty.',
        'return_page_seo_description.max_length' => 'Maximum length exceeded for SEO description on the Return Policy page (max 170 characters).',
        'return_page_content.permit_empty' => 'The Return Policy page content can be empty.',

        'refund_page_seo_title.permit_empty' => 'The Refund Policy page Tag title can be empty.',
        'refund_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the Refund Policy page (max 60 characters).',
        'refund_page_seo_keyword.permit_empty' => 'The Refund Policy page SEO keywords can be empty.',
        'refund_page_seo_keyword.max_length' => 'Maximum length exceeded for SEO keywords on the Refund Policy page (max 70 characters).',
        'refund_page_seo_description.permit_empty' => 'The Refund Policy page SEO description can be empty.',
        'refund_page_seo_description.max_length' => 'Maximum length exceeded for SEO description on the Refund Policy page (max 170 characters).',
        'refund_page_content.permit_empty' => 'The Refund Policy page content can be empty.',

        'disclaimer_page_seo_title.permit_empty' => 'The Disclaimer page Tag title can be empty.',
        'disclaimer_page_seo_title.max_length' => 'Maximum length exceeded for Tag title on the Disclaimer page (max 60 characters).',
        'disclaimer_page_seo_keyword.permit_empty' => 'The Disclaimer page SEO keywords can be empty.',
        'disclaimer_page_seo_keyword.max_length' => 'Maximum length exceeded for SEO keywords on the Disclaimer page (max 70 characters).',
        'disclaimer_page_seo_description.permit_empty' => 'The Disclaimer page SEO description can be empty.',
        'disclaimer_page_seo_description.max_length' => 'Maximum length exceeded for SEO description on the Disclaimer page (max 170 characters).',
        'disclaimer_page_content.permit_empty' => 'The Disclaimer page content can be empty.',

        //'level1.required' => 'Level 1 field is required.',
        'level1_commission_percentage.required' => 'Level 1 Commission Percentage field is required.',
        //'level2.required' => 'Level 2 field is required.',
        'level2_commission_percentage.required' => 'Level 2 Commission Percentage field is required.',
        //'wallet_activation_amount.required' => 'E-Wallet Activation Amount field is required.',
        // 'wallet_withdrawal_amount.required' => 'E-Wallet Withdrawal Amount field is required.',
        'pickup_location' => 'Pickup location is required. Please enter the exact pickup location name as configured in the Delhivery admin panel.'
    ];


    protected $skipValidation       = false;
    protected $cleanValidationRules = true;

    // Callbacks
    protected $allowCallbacks = true;
    protected $beforeInsert   = [];
    protected $afterInsert    = [];
    protected $beforeUpdate   = [];
    protected $afterUpdate    = [];
    protected $beforeFind     = [];
    protected $afterFind      = [];
    protected $beforeDelete   = [];
    protected $afterDelete    = [];

    public function __construct()
    {
        parent::__construct();
    }
}
